// Seed data for advertisements
export const adsData = [
  // Educational Services Ads
  {
    title: 'SmartClass Interactive Boards',
    description: 'Transform your classroom with modern interactive smart boards. Real-time engagement and digital content delivery.',
    advertiserName: 'SmartClass Technologies',
    advertiserEmail: 'contact@smartclasstech.com',
    advertiserPhone: '+91-9876501234',
    category: 'education-technology',
    adType: 'banner',
    placement: 'LP_TOP_BANNER',
    format: '970x250',
    imageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324ef6e2?w=970&h=250&fit=crop',
    landingUrl: 'https://smartclasstech.com',
    status: 'active',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    budget: 50000,
    impressions: 15000,
    clicks: 450,
    conversions: 12,
    targetRoles: ['institute'],
    targetStates: ['Delhi', 'NCR', 'Maharashtra', 'Karnataka'],
    priority: 'high',
    createdAt: new Date('2024-12-15'),
  },
  {
    title: 'Online Examination Portal - EduVision',
    description: 'Secure online assessment platform for schools. MCQ, descriptive, and proctored exams. Real-time result analysis.',
    advertiserName: 'EduVision Digital Learning',
    advertiserEmail: 'info@eduvisiondigital.in',
    advertiserPhone: '+91-9876502345',
    category: 'education-technology',
    adType: 'rectangle',
    placement: 'LIST_SIDEBAR',
    format: '336x280',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f70504504?w=336&h=280&fit=crop',
    landingUrl: 'https://eduvisiondigital.in',
    status: 'active',
    startDate: new Date('2026-01-05'),
    endDate: new Date('2026-12-31'),
    budget: 30000,
    impressions: 8500,
    clicks: 280,
    conversions: 8,
    targetRoles: ['institute'],
    targetStates: ['Karnataka', 'Tamil Nadu', 'Andhra Pradesh'],
    priority: 'medium',
    createdAt: new Date('2024-12-20'),
  },
  {
    title: 'School Bus Financing - Zero Down Payment',
    description: 'Flexible EMI plans for school buses. Quick approval, competitive rates. No hidden charges.',
    advertiserName: 'EduFleet Finance',
    advertiserEmail: 'finance@edufleetfinance.com',
    advertiserPhone: '+91-9876504567',
    category: 'finance',
    adType: 'skyscraper',
    placement: 'LP_INLINE_1',
    format: '300x600',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=300&h=600&fit=crop',
    landingUrl: 'https://edufleetfinance.com/bus-loans',
    status: 'active',
    startDate: new Date('2026-01-10'),
    endDate: new Date('2026-12-31'),
    budget: 75000,
    impressions: 22000,
    clicks: 680,
    conversions: 18,
    targetRoles: ['institute'],
    targetStates: ['All'],
    priority: 'high',
    createdAt: new Date('2024-12-10'),
  },
  {
    title: 'Teacher Professional Development Course',
    description: 'Upskill with our online teacher certification courses. CTET, TET, Subject Mastery programs.',
    advertiserName: 'TeachTech Institute',
    advertiserEmail: 'courses@teachtech.in',
    advertiserPhone: '+91-9876505678',
    category: 'professional-development',
    adType: 'banner',
    placement: 'DASH_TOP',
    format: '728x90',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=728&h=90&fit=crop',
    landingUrl: 'https://teachtech.in/courses',
    status: 'active',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    budget: 25000,
    impressions: 10500,
    clicks: 320,
    conversions: 28,
    targetRoles: ['teacher'],
    targetStates: ['All'],
    priority: 'medium',
    createdAt: new Date('2024-12-18'),
  },
  {
    title: 'School Management ERP Software',
    description: 'Complete school management solution. Attendance, fees, reports, and parent communication in one platform.',
    advertiserName: 'SchoolSync Solutions',
    advertiserEmail: 'sales@schoolsync.in',
    advertiserPhone: '+91-9876506789',
    category: 'education-technology',
    adType: 'rectangle',
    format: '300x250',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=300&h=250&fit=crop',
    landingUrl: 'https://schoolsync.in',
    status: 'approved',
    startDate: new Date('2025-01-08'),
    endDate: new Date('2025-03-20'),
    budget: 40000,
    impressions: 12000,
    clicks: 360,
    conversions: 15,
    targetRoles: ['institute'],
    targetStates: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad'],
    priority: 'medium',
    createdAt: new Date('2024-12-19'),
  },

  // Pending Approval Ads
  {
    title: 'Sports Equipment Supplier',
    description: 'Quality sports equipment and furniture for schools. Cricket, football, athletics, and indoor sports.',
    advertiserName: 'SportClass India',
    advertiserEmail: 'contact@sportclass.in',
    advertiserPhone: '+91-9876507890',
    category: 'sports-supplies',
    adType: 'banner',
    format: '970x250',
    imageUrl: 'https://images.unsplash.com/photo-1574438671057-11ad2f4cccf9?w=970&h=250&fit=crop',
    landingUrl: 'https://sportclass.in',
    status: 'pending',
    startDate: new Date('2025-02-01'),
    endDate: new Date('2025-04-30'),
    budget: 35000,
    impressions: 0,
    clicks: 0,
    conversions: 0,
    targetRoles: ['institute'],
    targetStates: ['All'],
    priority: 'low',
    createdAt: new Date('2024-12-25'),
  },
  {
    title: 'Catering Services for School Events',
    description: 'Professional catering for school functions, annual days, and special events. Nutritious, hygienic, and delicious food.',
    advertiserName: 'EduCatering Plus',
    advertiserEmail: 'bookings@educatering.in',
    advertiserPhone: '+91-9876508901',
    category: 'catering',
    adType: 'rectangle',
    format: '336x280',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561341?w=336&h=280&fit=crop',
    landingUrl: 'https://educatering.in',
    status: 'pending',
    startDate: new Date('2025-02-05'),
    endDate: new Date('2025-05-05'),
    budget: 28000,
    impressions: 0,
    clicks: 0,
    conversions: 0,
    targetRoles: ['institute'],
    targetStates: ['Maharashtra', 'Gujarat', 'Madhya Pradesh'],
    priority: 'low',
    createdAt: new Date('2024-12-24'),
  },

  // Rejected Ad (for reference)
  {
    title: 'Unknown Product X',
    description: 'Suspicious ad with unclear content',
    advertiserName: 'Unknown Advertiser',
    advertiserEmail: 'unknown@example.com',
    advertiserPhone: '+91-0000000000',
    category: 'other',
    adType: 'banner',
    format: '728x90',
    imageUrl: 'https://via.placeholder.com/728x90',
    landingUrl: 'https://example.com',
    status: 'rejected',
    rejectionReason: 'Unclear product and suspicious content',
    startDate: new Date('2024-12-20'),
    endDate: new Date('2024-12-22'),
    budget: 5000,
    impressions: 0,
    clicks: 0,
    conversions: 0,
    targetRoles: ['institute'],
    targetStates: ['All'],
    priority: 'low',
    createdAt: new Date('2024-12-22'),
  },
];

// Ad analytics sample data
export const adAnalyticsData = [
  {
    date: new Date('2025-01-15'),
    adId: 0, // References adsData[0] - SmartClass
    impressions: 500,
    clicks: 15,
    conversions: 1,
    cost: 500,
    revenue: 1500,
  },
  {
    date: new Date('2025-01-16'),
    adId: 0,
    impressions: 520,
    clicks: 18,
    conversions: 2,
    cost: 500,
    revenue: 1600,
  },
  {
    date: new Date('2025-01-17'),
    adId: 0,
    impressions: 480,
    clicks: 12,
    conversions: 1,
    cost: 500,
    revenue: 1400,
  },
  {
    date: new Date('2025-01-15'),
    adId: 2, // References adsData[2] - Finance
    impressions: 800,
    clicks: 25,
    conversions: 0,
    cost: 800,
    revenue: 1800,
  },
  {
    date: new Date('2025-01-16'),
    adId: 2,
    impressions: 750,
    clicks: 22,
    conversions: 1,
    cost: 800,
    revenue: 1900,
  },
];
