// Seed data for job listings and applications
export const jobsData = [
  // Active Jobs
  {
    title: 'Senior Mathematics Teacher (CBSE)',
    instituteName: 'Delhi Public School, R.K. Puram',
    location: {
      city: 'New Delhi',
      state: 'Delhi',
      country: 'India',
    },
    subjects: ['Mathematics', 'Advanced Mathematics'],
    experience: {
      min: 5,
      max: 12,
    },
    salary: {
      min: 45000,
      max: 75000,
      currency: 'INR',
    },
    qualification: ['B.Sc./M.Sc. Mathematics', 'B.Ed.', 'CTET/TET Qualified'],
    employmentType: 'full-time',
    description: 'We are seeking an experienced Mathematics teacher for senior secondary classes. The ideal candidate should have strong conceptual knowledge and ability to prepare students for competitive exams.',
    responsibilities: [
      'Teach Mathematics to classes 9-12',
      'Prepare students for Board exams and competitive exams',
      'Conduct regular assessments and provide feedback',
      'Maintain discipline and create engaging learning environment',
      'Participate in parent-teacher meetings and school events',
    ],
    requirements: [
      'Minimum 5 years teaching experience in CBSE schools',
      'Strong command over Mathematics curriculum',
      'Excellent communication and presentation skills',
      'Ability to use digital teaching tools',
      'Passion for teaching and mentoring students',
    ],
    benefits: [
      'Competitive salary package',
      'Health insurance',
      'Professional development opportunities',
      'Performance bonuses',
      'Transportation facility',
    ],
    contactEmail: 'hr@dpsrkpuram.edu',
    contactPhone: '+91-11-26101234',
    applicationDeadline: '2025-02-15',
    status: 'active',
    applicationsCount: 0,
  },
  {
    title: 'English Teacher (Primary Section)',
    instituteName: 'Kendriya Vidyalaya, Bandra',
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
    },
    subjects: ['English', 'English Language'],
    experience: {
      min: 2,
      max: 8,
    },
    salary: {
      min: 35000,
      max: 55000,
      currency: 'INR',
    },
    qualification: ['B.A. English', 'B.Ed.', 'CTET qualified'],
    employmentType: 'full-time',
    description: 'Looking for a dedicated English teacher for primary section (Classes 1-5). The candidate should be creative in teaching methods and passionate about early childhood education.',
    responsibilities: [
      'Teach English language and literature to primary students',
      'Develop age-appropriate lesson plans',
      'Assess student progress through assignments and tests',
      'Organize language-based activities and competitions',
      'Communicate regularly with parents about student progress',
    ],
    requirements: [
      'Graduate in English with B.Ed.',
      'Experience teaching primary classes',
      'Good command over English language',
      'Patient and child-friendly approach',
      'Basic computer skills',
    ],
    benefits: [
      'Government pay scale',
      'Medical benefits',
      'Paid leaves',
      'Pension benefits',
      'Educational allowances',
    ],
    contactEmail: 'principal@kvbandra.edu.in',
    contactPhone: '+91-22-26405678',
    applicationDeadline: '2025-01-30',
    status: 'active',
    applicationsCount: 0,
  },
  {
    title: 'Computer Science Faculty',
    instituteName: 'Modern School, Bangalore',
    location: {
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    subjects: ['Computer Science', 'Information Technology', 'Coding'],
    experience: {
      min: 3,
      max: 10,
    },
    salary: {
      min: 50000,
      max: 85000,
      currency: 'INR',
    },
    qualification: ['BCA/B.Tech/MCA/M.Tech', 'B.Ed. (preferred)', 'Certifications in programming languages'],
    employmentType: 'full-time',
    description: 'Seeking a tech-savvy Computer Science teacher who can teach programming, web development, and prepare students for future careers in technology.',
    responsibilities: [
      'Teach Computer Science for classes 6-12',
      'Train students in programming languages (Python, Java, C++)',
      'Guide students for coding competitions and hackathons',
      'Maintain and manage computer lab',
      'Stay updated with latest technology trends',
    ],
    requirements: [
      'Strong programming knowledge',
      'Experience with modern teaching tools and LMS',
      'Ability to teach both theory and practical',
      'Good problem-solving skills',
      'Enthusiasm for technology education',
    ],
    benefits: [
      'Attractive salary',
      'Latest technology resources',
      'Training and certifications',
      'Flexible teaching methods',
      'Performance incentives',
    ],
    contactEmail: 'careers@modernschoolblr.in',
    contactPhone: '+91-80-41234567',
    applicationDeadline: '2025-02-28',
    status: 'active',
    applicationsCount: 0,
  },
  {
    title: 'Science Teacher (Physics & Chemistry)',
    instituteName: 'DAV Public School, Pune',
    location: {
      city: 'Pune',
      state: 'Maharashtra',
      country: 'India',
    },
    subjects: ['Physics', 'Chemistry'],
    experience: {
      min: 4,
      max: 10,
    },
    salary: {
      min: 40000,
      max: 70000,
      currency: 'INR',
    },
    qualification: ['M.Sc. Physics/Chemistry', 'B.Ed.', 'TET/CTET qualified'],
    employmentType: 'full-time',
    description: 'We need an experienced Science teacher with expertise in both Physics and Chemistry. The candidate should make science interesting through practical demonstrations and experiments.',
    responsibilities: [
      'Teach Physics and Chemistry to classes 8-10',
      'Conduct laboratory experiments and demonstrations',
      'Prepare students for board exams',
      'Organize science exhibitions and fairs',
      'Maintain laboratory equipment and inventory',
    ],
    requirements: [
      'Post-graduate degree in Physics or Chemistry',
      'Strong laboratory skills',
      'Ability to explain complex concepts simply',
      'Good classroom management',
      'Safety consciousness in lab',
    ],
    benefits: [
      'Competitive salary',
      'Well-equipped science labs',
      'Annual increments',
      'Medical insurance',
      'Professional growth opportunities',
    ],
    contactEmail: 'admin@davpune.edu.in',
    contactPhone: '+91-20-26789012',
    applicationDeadline: '2025-02-10',
    status: 'active',
    applicationsCount: 0,
  },
  {
    title: 'Social Science Teacher',
    instituteName: "St. Xavier's School, Kolkata",
    location: {
      city: 'Kolkata',
      state: 'West Bengal',
      country: 'India',
    },
    subjects: ['History', 'Geography', 'Civics', 'Economics'],
    experience: {
      min: 3,
      max: 8,
    },
    salary: {
      min: 38000,
      max: 62000,
      currency: 'INR',
    },
    qualification: ['M.A. in History/Geography/Political Science', 'B.Ed.'],
    employmentType: 'full-time',
    description: 'Looking for a passionate Social Science teacher who can make history and geography come alive for students through interactive teaching methods.',
    responsibilities: [
      'Teach Social Science subjects to middle and senior classes',
      'Use maps, charts, and multimedia for effective teaching',
      'Organize educational tours and field trips',
      'Prepare students for competitive exams',
      'Conduct debates and quiz competitions',
    ],
    requirements: [
      'Masters degree in relevant subject',
      'Strong knowledge of CBSE/ICSE curriculum',
      'Good storytelling and presentation skills',
      'Ability to relate history to current affairs',
      'Interested in extracurricular activities',
    ],
    benefits: [
      'Good work environment',
      'Medical benefits',
      'Library access',
      'Professional development',
      'Transport allowance',
    ],
    contactEmail: 'recruitment@stxaviers-kol.edu',
    contactPhone: '+91-33-22876543',
    applicationDeadline: '2025-01-25',
    status: 'active',
    applicationsCount: 0,
  },
  {
    title: 'Primary Teacher (All Subjects)',
    instituteName: 'Ryan International School, Noida',
    location: {
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
    },
    subjects: ['All Primary Subjects', 'English', 'Mathematics', 'EVS'],
    experience: {
      min: 1,
      max: 5,
    },
    salary: {
      min: 30000,
      max: 50000,
      currency: 'INR',
    },
    qualification: ['Graduate', 'B.Ed./D.El.Ed.', 'CTET Paper 1'],
    employmentType: 'full-time',
    description: 'We are hiring enthusiastic primary teachers who love working with young children and can teach multiple subjects creatively.',
    responsibilities: [
      'Teach all subjects to primary classes (1-5)',
      'Create engaging lesson plans',
      'Assess and track student progress',
      'Organize classroom activities and games',
      'Regular communication with parents',
    ],
    requirements: [
      'Patience and love for teaching young children',
      'Good classroom management skills',
      'Creative and innovative teaching methods',
      'Good communication skills',
      'Team player',
    ],
    benefits: [
      'Training provided',
      'Career growth opportunities',
      'Friendly work environment',
      'Medical insurance',
      'Transport facility',
    ],
    contactEmail: 'hr@ryannoida.edu.in',
    contactPhone: '+91-120-2345678',
    applicationDeadline: '2025-02-05',
    status: 'active',
    applicationsCount: 0,
  },
  {
    title: 'Physical Education Teacher',
    instituteName: 'Amity International School, Gurgaon',
    location: {
      city: 'Gurgaon',
      state: 'Haryana',
      country: 'India',
    },
    subjects: ['Physical Education', 'Sports'],
    experience: {
      min: 3,
      max: 10,
    },
    salary: {
      min: 42000,
      max: 68000,
      currency: 'INR',
    },
    qualification: ['B.P.Ed./M.P.Ed.', 'Sports coaching certificates'],
    employmentType: 'full-time',
    description: 'Seeking an energetic PE teacher who can train students in various sports and promote overall fitness and wellness.',
    responsibilities: [
      'Conduct physical education classes',
      'Train students for inter-school competitions',
      'Organize sports day and athletic events',
      'Maintain sports equipment and facilities',
      'Promote health and fitness awareness',
    ],
    requirements: [
      'Degree in Physical Education',
      'Coaching experience in any sport',
      'Good physical fitness',
      'First aid knowledge',
      'Team management skills',
    ],
    benefits: [
      'Excellent sports facilities',
      'Performance bonuses',
      'Sports equipment allowance',
      'Medical coverage',
      'Professional coaching opportunities',
    ],
    contactEmail: 'sports@amitygurgaon.in',
    contactPhone: '+91-124-4567890',
    applicationDeadline: '2025-02-20',
    status: 'active',
    applicationsCount: 0,
  },
  {
    title: 'Art & Craft Teacher',
    instituteName: 'The Heritage School, Hyderabad',
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
      country: 'India',
    },
    subjects: ['Art', 'Craft', 'Drawing', 'Painting'],
    experience: {
      min: 2,
      max: 7,
    },
    salary: {
      min: 32000,
      max: 55000,
      currency: 'INR',
    },
    qualification: ['BFA/MFA', 'Teaching experience', 'Portfolio required'],
    employmentType: 'full-time',
    description: 'Looking for a creative Art teacher who can nurture artistic talent in students and organize art exhibitions and competitions.',
    responsibilities: [
      'Teach art and craft to all age groups',
      'Organize art competitions and exhibitions',
      'Maintain art room and supplies',
      'Guide students for art-related competitions',
      'Introduce various art forms and techniques',
    ],
    requirements: [
      'Fine Arts degree',
      'Proficiency in various art forms',
      'Creative and patient',
      'Portfolio of own artwork',
      'Good with children',
    ],
    benefits: [
      'Creative work environment',
      'Art supplies provided',
      'Exhibition opportunities',
      'Medical benefits',
      'Professional growth',
    ],
    contactEmail: 'admin@heritagehyd.edu.in',
    contactPhone: '+91-40-23456789',
    applicationDeadline: '2025-02-12',
    status: 'active',
    applicationsCount: 0,
  },

  // Part-time positions
  {
    title: 'Hindi Teacher (Part-time)',
    instituteName: 'Modern School, Bangalore',
    location: {
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
    },
    subjects: ['Hindi', 'Hindi Literature'],
    experience: {
      min: 2,
      max: 8,
    },
    salary: {
      min: 18000,
      max: 30000,
      currency: 'INR',
    },
    qualification: ['M.A. Hindi', 'B.Ed.'],
    employmentType: 'part-time',
    description: 'Part-time Hindi teacher needed for classes 6-10. 3-4 hours per day, flexible timings.',
    responsibilities: [
      'Teach Hindi language and literature',
      'Prepare lesson plans',
      'Assess student work',
      'Organize Hindi literary activities',
    ],
    requirements: [
      'Strong Hindi language skills',
      'Teaching experience',
      'Good communication',
      'Flexible with timings',
    ],
    benefits: [
      'Flexible hours',
      'Competitive hourly rate',
      'Friendly environment',
    ],
    contactEmail: 'part-time@modernschoolblr.in',
    contactPhone: '+91-80-41234567',
    applicationDeadline: '2025-01-31',
    status: 'active',
    applicationsCount: 0,
  },
  {
    title: 'Music Teacher (Contract)',
    instituteName: 'Ryan International School, Noida',
    location: {
      city: 'Noida',
      state: 'Uttar Pradesh',
      country: 'India',
    },
    subjects: ['Music', 'Vocal Music', 'Instrumental Music'],
    experience: {
      min: 1,
      max: 5,
    },
    salary: {
      min: 25000,
      max: 40000,
      currency: 'INR',
    },
    qualification: ['Music degree/diploma', 'Performance experience'],
    employmentType: 'contract',
    description: 'Contract position for 1 year. Looking for a music teacher who can teach both vocal and instrumental music.',
    responsibilities: [
      'Conduct music classes',
      'Train students for competitions',
      'Organize music events',
      'Maintain musical instruments',
    ],
    requirements: [
      'Music qualification',
      'Teaching/performance experience',
      'Proficiency in at least one instrument',
      'Ability to teach vocal music',
    ],
    benefits: [
      'Music room access',
      'Performance opportunities',
      'Extension possibility',
    ],
    contactEmail: 'music@ryannoida.edu.in',
    contactPhone: '+91-120-2345678',
    applicationDeadline: '2025-02-01',
    status: 'active',
    applicationsCount: 0,
  },
];

// Applications data (will be linked to jobs and teachers)
export const applicationsData = [
  // These will be populated after users and jobs are created
  // Structure for reference:
  // {
  //   jobId: 'ObjectId reference',
  //   teacherId: 'ObjectId reference',
  //   teacherName: 'Teacher name',
  //   instituteId: 'ObjectId reference',
  //   instituteName: 'Institute name',
  //   coverLetter: 'Cover letter content',
  //   status: 'pending',
  //   appliedDate: new Date(),
  // }
];
