// Seed data for suppliers
export const suppliersData = [
  // EduTech Suppliers
  {
    name: 'SmartClass Technologies',
    category: 'edutech',
    description: 'Leading provider of smart classroom solutions, interactive whiteboards, and digital learning platforms. We help schools transform traditional classrooms into modern digital learning spaces.',
    services: [
      'Interactive Smart Boards',
      'Digital Content Library',
      'Learning Management System',
      'Teacher Training',
      'Virtual Labs',
      'Student Assessment Tools',
    ],
    contactPerson: 'Rajesh Kumar',
    email: 'contact@smartclasstech.com',
    phone: '+91-9876501234',
    website: 'https://smartclasstech.com',
    address: {
      street: 'Tech Park, Sector 18',
      city: 'Gurgaon',
      state: 'Haryana',
      pincode: '122015',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=smartclass',
    certifications: ['ISO 9001:2015', 'MSME Certified', 'Startup India'],
    yearsInBusiness: 8,
    clientCount: 450,
    isVerified: true,
    status: 'approved',
  },
  {
    name: 'EduVision Digital Learning',
    category: 'edutech',
    description: 'Comprehensive digital learning solutions including e-learning platforms, educational apps, and online assessment tools for schools and coaching institutes.',
    services: [
      'E-Learning Platform',
      'Mobile Learning Apps',
      'Online Examination System',
      'Video Lectures',
      'Progress Analytics',
      'Parent Communication Portal',
    ],
    contactPerson: 'Priya Sharma',
    email: 'info@eduvisiondigital.in',
    phone: '+91-9876502345',
    website: 'https://eduvisiondigital.in',
    address: {
      street: 'IT Hub, Phase 2',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560100',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=eduvision',
    certifications: ['ISO 27001', 'Google for Education Partner'],
    yearsInBusiness: 6,
    clientCount: 320,
    isVerified: true,
    status: 'approved',
  },

  // Stationery Suppliers
  {
    name: 'Academic Stationery Mart',
    category: 'stationery',
    description: 'Complete range of educational stationery, office supplies, and art materials. Bulk orders with special discounts for educational institutions.',
    services: [
      'Notebooks & Registers',
      'Writing Instruments',
      'Art & Craft Supplies',
      'Files & Folders',
      'Whiteboards & Markers',
      'Geometry Boxes',
    ],
    contactPerson: 'Amit Patel',
    email: 'orders@academicstationery.com',
    phone: '+91-9876503456',
    website: 'https://academicstationery.com',
    address: {
      street: 'Stationery Complex, Station Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=stationery',
    certifications: ['MSME Registered', 'Quality Assured'],
    yearsInBusiness: 15,
    clientCount: 680,
    isVerified: true,
    status: 'approved',
  },
  {
    name: 'SchoolCart Supplies',
    category: 'stationery',
    description: 'One-stop shop for all school stationery needs. We offer customized products with school branding and doorstep delivery.',
    services: [
      'Customized Notebooks',
      'School Diaries',
      'ID Cards & Lanyards',
      'Certificates & Folders',
      'Notice Boards',
      'Teacher Planners',
    ],
    contactPerson: 'Sunita Deshmukh',
    email: 'sales@schoolcart.in',
    phone: '+91-9876504567',
    website: 'https://schoolcart.in',
    address: {
      street: 'Market Yard',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411037',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=schoolcart',
    certifications: ['MSME Certified'],
    yearsInBusiness: 10,
    clientCount: 425,
    isVerified: true,
    status: 'approved',
  },

  // Furniture Suppliers
  {
    name: 'ErgoClass Furniture',
    category: 'furniture',
    description: 'Ergonomic school furniture manufacturer specializing in student desks, chairs, and classroom furniture. Focus on comfort and durability.',
    services: [
      'Student Desks & Chairs',
      'Library Furniture',
      'Laboratory Furniture',
      'Staff Room Furniture',
      'Auditorium Seating',
      'Storage Solutions',
    ],
    contactPerson: 'Vikram Malhotra',
    email: 'sales@ergoclass.com',
    phone: '+91-9876505678',
    website: 'https://ergoclass.com',
    address: {
      street: 'Industrial Area, Phase 4',
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110020',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=ergoclass',
    certifications: ['ISO 9001:2015', 'Green Product Certified'],
    yearsInBusiness: 12,
    clientCount: 550,
    isVerified: true,
    status: 'approved',
  },
  {
    name: 'ClassComfort Solutions',
    category: 'furniture',
    description: 'Modern classroom furniture with focus on flexibility and sustainability. Customized solutions for different educational settings.',
    services: [
      'Modular Classroom Furniture',
      'Height-Adjustable Desks',
      'Collaborative Learning Tables',
      'Teacher Workstations',
      'Storage Cabinets',
      'Outdoor Furniture',
    ],
    contactPerson: 'Meera Singh',
    email: 'info@classcomfort.in',
    phone: '+91-9876506789',
    website: 'https://classcomfort.in',
    address: {
      street: 'Furniture Hub, Sector 63',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201301',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=classcomfort',
    certifications: ['FSC Certified', 'BIFMA Standards'],
    yearsInBusiness: 8,
    clientCount: 380,
    isVerified: true,
    status: 'approved',
  },

  // Technology Suppliers
  {
    name: 'TechEdu Systems',
    category: 'technology',
    description: 'IT infrastructure solutions for educational institutions. From computer labs to networking and security systems.',
    services: [
      'Computer Lab Setup',
      'Network Infrastructure',
      'Server Solutions',
      'CCTV & Security Systems',
      'Biometric Attendance',
      'IT Support & Maintenance',
    ],
    contactPerson: 'Karthik Reddy',
    email: 'support@techedu.in',
    phone: '+91-9876507890',
    website: 'https://techedu.in',
    address: {
      street: 'Cyber Towers, HITEC City',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500081',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=techedu',
    certifications: ['ISO 27001', 'Microsoft Partner', 'Cisco Certified'],
    yearsInBusiness: 9,
    clientCount: 290,
    isVerified: true,
    status: 'approved',
  },
  {
    name: 'Digital Campus Solutions',
    category: 'technology',
    description: 'Complete digital transformation solutions for schools including ERP systems, campus management software, and smart attendance.',
    services: [
      'School ERP System',
      'Attendance Management',
      'Fee Management Software',
      'Transport Management',
      'Library Management',
      'Hostel Management',
    ],
    contactPerson: 'Neha Gupta',
    email: 'contact@digitalcampus.co.in',
    phone: '+91-9876508901',
    website: 'https://digitalcampus.co.in',
    address: {
      street: 'Software Park',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600113',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=digitalcampus',
    certifications: ['ISO 9001', 'NASSCOM Member'],
    yearsInBusiness: 7,
    clientCount: 410,
    isVerified: true,
    status: 'approved',
  },

  // Sports Equipment Suppliers
  {
    name: 'Champions Sports Equipment',
    category: 'sports',
    description: 'Complete range of sports equipment for schools including indoor and outdoor games, gym equipment, and sports uniforms.',
    services: [
      'Cricket Equipment',
      'Football & Basketball',
      'Athletics Equipment',
      'Indoor Games',
      'Gym Equipment',
      'Sports Uniforms',
    ],
    contactPerson: 'Arjun Singh',
    email: 'orders@championssports.in',
    phone: '+91-9876509012',
    website: 'https://championssports.in',
    address: {
      street: 'Sports Complex Road',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302019',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=champions',
    certifications: ['ISI Marked Products', 'Sports Authority Approved'],
    yearsInBusiness: 11,
    clientCount: 520,
    isVerified: true,
    status: 'approved',
  },

  // Library Suppliers
  {
    name: 'BookHub Library Solutions',
    category: 'library',
    description: 'Complete library setup and management solutions. From books to library furniture and digital cataloging systems.',
    services: [
      'Library Books Supply',
      'Library Furniture',
      'Digital Library System',
      'Book Cataloging',
      'Magazine Subscriptions',
      'Reading Room Setup',
    ],
    contactPerson: 'Sanjay Kumar',
    email: 'info@bookhubsolutions.com',
    phone: '+91-9876510123',
    website: 'https://bookhubsolutions.com',
    address: {
      street: 'Book Market',
      city: 'Kolkata',
      state: 'West Bengal',
      pincode: '700016',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=bookhub',
    certifications: ['Library Association Member'],
    yearsInBusiness: 14,
    clientCount: 470,
    isVerified: true,
    status: 'approved',
  },

  // Lab Equipment Suppliers
  {
    name: 'ScienceLab Pro',
    category: 'lab-equipment',
    description: 'Scientific laboratory equipment and supplies for schools. Complete lab setup services for Physics, Chemistry, and Biology.',
    services: [
      'Physics Lab Equipment',
      'Chemistry Lab Setup',
      'Biology Lab Supplies',
      'Lab Furniture',
      'Safety Equipment',
      'Lab Maintenance',
    ],
    contactPerson: 'Dr. Ravi Verma',
    email: 'sales@sciencelabpro.in',
    phone: '+91-9876511234',
    website: 'https://sciencelabpro.in',
    address: {
      street: 'Industrial Estate',
      city: 'Ahmedabad',
      state: 'Gujarat',
      pincode: '380015',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=sciencelab',
    certifications: ['ISO 9001', 'Laboratory Standards Certified'],
    yearsInBusiness: 10,
    clientCount: 340,
    isVerified: true,
    status: 'approved',
  },

  // Pending Approval Suppliers
  {
    name: 'GreenBoard Eco Supplies',
    category: 'stationery',
    description: 'Eco-friendly stationery and school supplies. Committed to sustainability with recycled and biodegradable products.',
    services: [
      'Recycled Paper Products',
      'Eco-friendly Stationery',
      'Biodegradable Pens',
      'Sustainable Packaging',
      'Green Craft Supplies',
    ],
    contactPerson: 'Lakshmi Iyer',
    email: 'contact@greenboard.eco',
    phone: '+91-9876512345',
    website: 'https://greenboard.eco',
    address: {
      street: 'Eco Park',
      city: 'Cochin',
      state: 'Kerala',
      pincode: '682020',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=greenboard',
    certifications: ['Green Business Certified', 'FSC Certified'],
    yearsInBusiness: 3,
    clientCount: 85,
    isVerified: false,
    status: 'pending',
  },
  {
    name: 'RoboLearn STEM Labs',
    category: 'edutech',
    description: 'Robotics and STEM education kits for schools. Hands-on learning solutions for future innovators.',
    services: [
      'Robotics Kits',
      'STEM Lab Setup',
      'Coding Education Platforms',
      '3D Printing Solutions',
      'Teacher Training Programs',
      'Competition Support',
    ],
    contactPerson: 'Ankit Desai',
    email: 'info@robolearn.tech',
    phone: '+91-9876513456',
    website: 'https://robolearn.tech',
    address: {
      street: 'Innovation Hub',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411045',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=robolearn',
    certifications: ['Startup India', 'Innovation Award 2024'],
    yearsInBusiness: 2,
    clientCount: 65,
    isVerified: false,
    status: 'pending',
  },
  {
    name: 'SafeSchool Security Systems',
    category: 'technology',
    description: 'Comprehensive school security solutions including CCTV, access control, and emergency response systems.',
    services: [
      'CCTV Surveillance',
      'Access Control Systems',
      'Emergency Alarms',
      'Visitor Management',
      'Fire Safety Systems',
      '24/7 Monitoring',
    ],
    contactPerson: 'Rohit Thakur',
    email: 'security@safeschool.in',
    phone: '+91-9876514567',
    website: 'https://safeschool.in',
    address: {
      street: 'Security Plaza, Sector 8',
      city: 'Chandigarh',
      state: 'Chandigarh',
      pincode: '160008',
      country: 'India',
    },
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=safeschool',
    certifications: ['Security Systems Certified'],
    yearsInBusiness: 5,
    clientCount: 120,
    isVerified: false,
    status: 'pending',
  },
];
