import bcrypt from 'bcryptjs';

// Generate hashed passwords
const hashPassword = (password: string) => bcrypt.hashSync(password, 10);

// Seed data for users (Institutes, Teachers, Admin)
export const usersData = [
  // Admin Users
  {
    name: 'Super Admin',
    email: 'admin@edufleet.com',
    password: hashPassword('admin123'),
    role: 'admin',
    instituteName: 'EduFleet Exchange',
    contactPerson: 'System Administrator',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
  },
  {
    name: 'Support Admin',
    email: 'support@edufleet.com',
    password: hashPassword('support123'),
    role: 'admin',
    instituteName: 'EduFleet Exchange',
    contactPerson: 'Support Team',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=support',
  },

  // Institute Users
  {
    name: 'Delhi Public School',
    email: 'dps.delhi@institute.com',
    password: hashPassword('institute123'),
    role: 'institute',
    instituteName: 'Delhi Public School, R.K. Puram',
    contactPerson: 'Rajesh Kumar',
    phone: '+91-9876543210',
    address: {
      street: 'Sector 12',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110022',
      country: 'India',
    },
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=DPS',
  },
  {
    name: 'Kendriya Vidyalaya',
    email: 'kv.mumbai@institute.com',
    password: hashPassword('institute123'),
    role: 'institute',
    instituteName: 'Kendriya Vidyalaya, Bandra',
    contactPerson: 'Priya Sharma',
    phone: '+91-9876543211',
    address: {
      street: 'Hill Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
      country: 'India',
    },
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=KV',
  },
  {
    name: 'Modern School',
    email: 'modern.bangalore@institute.com',
    password: hashPassword('institute123'),
    role: 'institute',
    instituteName: 'Modern School, Bangalore',
    contactPerson: 'Amit Patel',
    phone: '+91-9876543212',
    address: {
      street: 'Indiranagar',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560038',
      country: 'India',
    },
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=MS',
  },
  {
    name: 'DAV Public School',
    email: 'dav.pune@institute.com',
    password: hashPassword('institute123'),
    role: 'institute',
    instituteName: 'DAV Public School, Pune',
    contactPerson: 'Sunita Deshmukh',
    phone: '+91-9876543213',
    address: {
      street: 'Koregaon Park',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      country: 'India',
    },
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=DAV',
  },
  {
    name: 'St. Xavier School',
    email: 'stxavier.kolkata@institute.com',
    password: hashPassword('institute123'),
    role: 'institute',
    instituteName: "St. Xavier's School, Kolkata",
    contactPerson: 'Father Thomas',
    phone: '+91-9876543214',
    address: {
      street: 'Park Street',
      city: 'Kolkata',
      state: 'West Bengal',
      pincode: '700016',
      country: 'India',
    },
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=SX',
  },
  {
    name: 'Ryan International',
    email: 'ryan.noida@institute.com',
    password: hashPassword('institute123'),
    role: 'institute',
    instituteName: 'Ryan International School, Noida',
    contactPerson: 'Meera Singh',
    phone: '+91-9876543215',
    address: {
      street: 'Sector 25',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201301',
      country: 'India',
    },
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=RI',
  },
  {
    name: 'Amity International',
    email: 'amity.gurgaon@institute.com',
    password: hashPassword('institute123'),
    role: 'institute',
    instituteName: 'Amity International School, Gurgaon',
    contactPerson: 'Vikram Malhotra',
    phone: '+91-9876543216',
    address: {
      street: 'Sector 46',
      city: 'Gurgaon',
      state: 'Haryana',
      pincode: '122003',
      country: 'India',
    },
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=AI',
  },
  {
    name: 'The Heritage School',
    email: 'heritage.hyderabad@institute.com',
    password: hashPassword('institute123'),
    role: 'institute',
    instituteName: 'The Heritage School, Hyderabad',
    contactPerson: 'Lakshmi Reddy',
    phone: '+91-9876543217',
    address: {
      street: 'Jubilee Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500033',
      country: 'India',
    },
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=TH',
  },

  // Teacher Users
  {
    name: 'Anjali Verma',
    email: 'anjali.verma@teacher.com',
    password: hashPassword('teacher123'),
    role: 'teacher',
    phone: '+91-9123456781',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anjali',
    profile: {
      qualification: ['B.Ed.', 'M.A. English'],
      subjects: ['English', 'English Literature'],
      experience: 8,
      currentInstitute: 'St. Mary\'s School',
      preferredLocation: ['Delhi', 'Gurgaon', 'Noida'],
      achievements: [
        'Best Teacher Award 2022',
        'Published research on modern teaching methods',
      ],
    },
  },
  {
    name: 'Rahul Sharma',
    email: 'rahul.sharma@teacher.com',
    password: hashPassword('teacher123'),
    role: 'teacher',
    phone: '+91-9123456782',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rahul',
    profile: {
      qualification: ['B.Sc.', 'B.Ed.', 'M.Sc. Mathematics'],
      subjects: ['Mathematics', 'Physics'],
      experience: 12,
      currentInstitute: 'Delhi Public School',
      preferredLocation: ['Delhi', 'Mumbai', 'Bangalore'],
      achievements: [
        'Trained 500+ students for competitive exams',
        'Mathematics Olympiad Coach',
      ],
    },
  },
  {
    name: 'Priya Menon',
    email: 'priya.menon@teacher.com',
    password: hashPassword('teacher123'),
    role: 'teacher',
    phone: '+91-9123456783',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    profile: {
      qualification: ['B.Sc.', 'B.Ed.', 'M.Sc. Chemistry'],
      subjects: ['Chemistry', 'Biology'],
      experience: 6,
      currentInstitute: 'Kendriya Vidyalaya',
      preferredLocation: ['Bangalore', 'Hyderabad', 'Chennai'],
      achievements: [
        'Science Fair Coordinator',
        'Published papers in education journals',
      ],
    },
  },
  {
    name: 'Vikram Singh',
    email: 'vikram.singh@teacher.com',
    password: hashPassword('teacher123'),
    role: 'teacher',
    phone: '+91-9123456784',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vikram',
    profile: {
      qualification: ['B.A.', 'B.Ed.', 'M.A. History'],
      subjects: ['History', 'Social Science', 'Political Science'],
      experience: 10,
      currentInstitute: 'Modern School',
      preferredLocation: ['Pune', 'Mumbai', 'Kolkata'],
      achievements: [
        'Quiz Master for State Level Competitions',
        'Heritage Club Coordinator',
      ],
    },
  },
  {
    name: 'Sneha Kapoor',
    email: 'sneha.kapoor@teacher.com',
    password: hashPassword('teacher123'),
    role: 'teacher',
    phone: '+91-9123456785',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sneha',
    profile: {
      qualification: ['BCA', 'B.Ed.', 'M.Sc. Computer Science'],
      subjects: ['Computer Science', 'Information Technology'],
      experience: 5,
      currentInstitute: 'Ryan International',
      preferredLocation: ['Noida', 'Gurgaon', 'Delhi'],
      achievements: [
        'Coding Club Mentor',
        'Trained students for international coding competitions',
      ],
    },
  },
  {
    name: 'Karthik Reddy',
    email: 'karthik.reddy@teacher.com',
    password: hashPassword('teacher123'),
    role: 'teacher',
    phone: '+91-9123456786',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=karthik',
    profile: {
      qualification: ['B.A.', 'B.Ed.', 'M.A. Economics'],
      subjects: ['Economics', 'Business Studies', 'Accountancy'],
      experience: 9,
      currentInstitute: 'DAV Public School',
      preferredLocation: ['Hyderabad', 'Bangalore', 'Chennai'],
      achievements: [
        'Economics Club Coordinator',
        'Guest lecturer at university workshops',
      ],
    },
  },
  {
    name: 'Megha Nair',
    email: 'megha.nair@teacher.com',
    password: hashPassword('teacher123'),
    role: 'teacher',
    phone: '+91-9123456787',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=megha',
    profile: {
      qualification: ['B.A.', 'B.Ed.', 'M.A. Geography'],
      subjects: ['Geography', 'Environmental Science'],
      experience: 7,
      currentInstitute: 'St. Xavier School',
      preferredLocation: ['Kolkata', 'Delhi', 'Pune'],
      achievements: [
        'Eco Club Coordinator',
        'Organized state-level environmental awareness campaigns',
      ],
    },
  },
  {
    name: 'Arjun Patel',
    email: 'arjun.patel@teacher.com',
    password: hashPassword('teacher123'),
    role: 'teacher',
    phone: '+91-9123456788',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arjun',
    profile: {
      qualification: ['B.P.Ed.', 'M.P.Ed.'],
      subjects: ['Physical Education', 'Sports'],
      experience: 11,
      currentInstitute: 'Amity International',
      preferredLocation: ['Gurgaon', 'Delhi', 'Mumbai'],
      achievements: [
        'State Level Basketball Coach',
        'Sports Day Coordinator for 5+ years',
      ],
    },
  },
  {
    name: 'Neha Gupta',
    email: 'neha.gupta@teacher.com',
    password: hashPassword('teacher123'),
    role: 'teacher',
    phone: '+91-9123456789',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=neha',
    profile: {
      qualification: ['B.A.', 'B.Ed.', 'M.A. Hindi'],
      subjects: ['Hindi', 'Sanskrit'],
      experience: 6,
      currentInstitute: 'The Heritage School',
      preferredLocation: ['Hyderabad', 'Pune', 'Bangalore'],
      achievements: [
        'Literary Club Coordinator',
        'Published Hindi poetry collection',
      ],
    },
  },
  {
    name: 'Sanjay Kumar',
    email: 'sanjay.kumar@teacher.com',
    password: hashPassword('teacher123'),
    role: 'teacher',
    phone: '+91-9123456790',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sanjay',
    profile: {
      qualification: ['B.Sc.', 'B.Ed.', 'M.Sc. Physics'],
      subjects: ['Physics', 'Mathematics'],
      experience: 14,
      currentInstitute: 'Delhi Public School',
      preferredLocation: ['Delhi', 'Noida', 'Gurgaon'],
      achievements: [
        'Science Olympiad Trainer',
        'Robotics Club Mentor',
      ],
    },
  },
];

// Plain passwords for reference (DO NOT STORE IN DATABASE)
export const userCredentials = {
  admin: {
    email: 'admin@edufleet.com',
    password: 'admin123',
  },
  support: {
    email: 'support@edufleet.com',
    password: 'support123',
  },
  institute: {
    email: 'dps.delhi@institute.com',
    password: 'institute123',
  },
  teacher: {
    email: 'anjali.verma@teacher.com',
    password: 'teacher123',
  },
};
