// Seed data for vehicles
export const vehiclesData = [
  // School Buses
  {
    title: 'Tata LP 909 School Bus - 42 Seater',
    manufacturer: 'Tata Motors',
    vehicleModel: 'LP 909',
    year: 2020,
    type: 'school-bus',
    price: 1250000,
    registrationNumber: 'DL-1A-1234',
    mileage: 45000,
    condition: 'excellent',
    features: ['GPS Tracking', 'CCTV Cameras', 'Fire Extinguisher', 'First Aid Kit', 'Speed Governor', 'Emergency Exit'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800',
    ],
    description: 'Well-maintained school bus with all safety features. Regular servicing done. Perfect for educational institutions looking for reliable transportation.',
    isPriority: true,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2026-03-15',
      provider: 'HDFC Ergo',
    },
    fitness: {
      valid: true,
      expiryDate: '2025-12-30',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-01-20',
    },
    permit: {
      valid: true,
      expiryDate: '2026-02-10',
      permitType: 'State Permit',
    },
  },
  {
    title: 'Ashok Leyland Viking School Bus - 52 Seater',
    manufacturer: 'Ashok Leyland',
    vehicleModel: 'Viking',
    year: 2019,
    type: 'school-bus',
    price: 1450000,
    registrationNumber: 'MH-2B-5678',
    mileage: 62000,
    condition: 'excellent',
    features: ['GPS Tracking', 'CCTV Cameras', 'Air Conditioning', 'Push Back Seats', 'Speed Governor', 'Emergency Exit', 'Audio System'],
    images: [
      'https://images.unsplash.com/photo-1570125909517-53cb21c89ff2?w=800',
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    description: 'Premium AC school bus with excellent condition. Low mileage, well-maintained by previous owner. All documents clear.',
    isPriority: true,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2025-11-20',
      provider: 'National Insurance',
    },
    fitness: {
      valid: true,
      expiryDate: '2026-01-15',
    },
    roadTax: {
      valid: true,
      expiryDate: '2025-12-31',
    },
    permit: {
      valid: true,
      expiryDate: '2026-03-01',
      permitType: 'All India Permit',
    },
  },
  {
    title: 'Mahindra Tourister School Bus - 35 Seater',
    manufacturer: 'Mahindra',
    vehicleModel: 'Tourister',
    year: 2021,
    type: 'school-bus',
    price: 950000,
    registrationNumber: 'KA-3C-9012',
    mileage: 28000,
    condition: 'excellent',
    features: ['GPS Tracking', 'CCTV Cameras', 'First Aid Kit', 'Fire Extinguisher', 'Speed Governor'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    description: 'Nearly new condition school bus, ideal for small to medium institutes. Fuel efficient with modern safety features.',
    isPriority: false,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2026-06-30',
      provider: 'ICICI Lombard',
    },
    fitness: {
      valid: true,
      expiryDate: '2026-05-20',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-04-15',
    },
    permit: {
      valid: true,
      expiryDate: '2026-07-01',
      permitType: 'State Permit',
    },
  },
  {
    title: 'Force Traveller School Bus - 26 Seater',
    manufacturer: 'Force Motors',
    vehicleModel: 'Traveller',
    year: 2018,
    type: 'school-bus',
    price: 650000,
    registrationNumber: 'TN-4D-3456',
    mileage: 85000,
    condition: 'good',
    features: ['GPS Tracking', 'CCTV Cameras', 'Speed Governor', 'Emergency Exit'],
    images: [
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800',
    ],
    description: 'Compact school bus perfect for smaller routes. Regular maintenance records available. Good fuel economy.',
    isPriority: false,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2025-10-15',
      provider: 'Bajaj Allianz',
    },
    fitness: {
      valid: true,
      expiryDate: '2025-11-30',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-01-10',
    },
    permit: {
      valid: true,
      expiryDate: '2025-12-20',
      permitType: 'State Permit',
    },
  },

  // Minibuses
  {
    title: 'Tempo Traveller 17 Seater - Deluxe Model',
    manufacturer: 'Force Motors',
    vehicleModel: 'Tempo Traveller',
    year: 2020,
    type: 'minibus',
    price: 750000,
    registrationNumber: 'DL-5E-7890',
    mileage: 42000,
    condition: 'excellent',
    features: ['Air Conditioning', 'Push Back Seats', 'Music System', 'LED Lights', 'Curtains'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    description: 'Luxury tempo traveller in excellent condition. Perfect for institute tours and educational trips.',
    isPriority: true,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2026-02-28',
      provider: 'SBI General',
    },
    fitness: {
      valid: true,
      expiryDate: '2026-03-15',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-01-30',
    },
    permit: {
      valid: true,
      expiryDate: '2026-04-10',
      permitType: 'All India Permit',
    },
  },
  {
    title: 'Mahindra Tourister 13 Seater',
    manufacturer: 'Mahindra',
    vehicleModel: 'Tourister COSMO',
    year: 2019,
    type: 'minibus',
    price: 580000,
    registrationNumber: 'GJ-6F-1122',
    mileage: 55000,
    condition: 'good',
    features: ['Air Conditioning', 'Comfortable Seating', 'Music System', 'Storage Space'],
    images: [
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800',
    ],
    description: 'Well-maintained 13-seater minibus. Ideal for small group transportation and educational field trips.',
    isPriority: false,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2025-12-15',
      provider: 'Reliance General',
    },
    fitness: {
      valid: true,
      expiryDate: '2026-02-20',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-03-10',
    },
    permit: {
      valid: true,
      expiryDate: '2026-01-25',
      permitType: 'State Permit',
    },
  },

  // Vans
  {
    title: 'Maruti Suzuki Eeco 7 Seater Van',
    manufacturer: 'Maruti Suzuki',
    vehicleModel: 'Eeco',
    year: 2021,
    type: 'van',
    price: 380000,
    registrationNumber: 'RJ-7G-3344',
    mileage: 32000,
    condition: 'excellent',
    features: ['Air Conditioning', 'Power Steering', 'Central Locking', 'Music System'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    description: 'Compact and fuel-efficient van perfect for staff transportation and small errands. Low maintenance cost.',
    isPriority: false,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2026-05-30',
      provider: 'TATA AIG',
    },
    fitness: {
      valid: true,
      expiryDate: '2026-06-15',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-04-20',
    },
    permit: {
      valid: false,
      expiryDate: '2024-12-31',
      permitType: 'State Permit',
    },
  },
  {
    title: 'Tata Winger 9 Seater Executive Van',
    manufacturer: 'Tata Motors',
    vehicleModel: 'Winger',
    year: 2019,
    type: 'van',
    price: 680000,
    registrationNumber: 'UP-8H-5566',
    mileage: 48000,
    condition: 'good',
    features: ['Air Conditioning', 'Captain Seats', 'LED Lights', 'Entertainment System', 'Premium Interiors'],
    images: [
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800',
    ],
    description: 'Executive van with premium features. Excellent for VIP guest transportation and administrative use.',
    isPriority: false,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2025-11-10',
      provider: 'Oriental Insurance',
    },
    fitness: {
      valid: true,
      expiryDate: '2026-01-05',
    },
    roadTax: {
      valid: true,
      expiryDate: '2025-12-25',
    },
    permit: {
      valid: true,
      expiryDate: '2026-02-15',
      permitType: 'State Permit',
    },
  },

  // Trucks
  {
    title: 'Tata 407 Pickup Truck - 2.5 Ton',
    manufacturer: 'Tata Motors',
    vehicleModel: '407',
    year: 2018,
    type: 'truck',
    price: 550000,
    registrationNumber: 'HR-9I-7788',
    mileage: 95000,
    condition: 'good',
    features: ['Power Steering', 'Strong Chassis', 'Spare Tire', 'Tool Kit'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    description: 'Reliable pickup truck for transporting institute supplies, furniture, and equipment. Strong engine.',
    isPriority: false,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2025-10-30',
      provider: 'United India Insurance',
    },
    fitness: {
      valid: true,
      expiryDate: '2025-12-10',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-01-15',
    },
    permit: {
      valid: true,
      expiryDate: '2025-11-20',
      permitType: 'Goods Carrier',
    },
  },
  {
    title: 'Mahindra Bolero Pickup - 1.5 Ton',
    manufacturer: 'Mahindra',
    vehicleModel: 'Bolero Pickup',
    year: 2020,
    type: 'truck',
    price: 480000,
    registrationNumber: 'MP-10J-9900',
    mileage: 38000,
    condition: 'excellent',
    features: ['4WD', 'Power Steering', 'Strong Suspension', 'Load Carrier'],
    images: [
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800',
    ],
    description: 'Robust pickup truck with 4-wheel drive. Perfect for institutes in hilly or rural areas. Low mileage.',
    isPriority: false,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2026-04-15',
      provider: 'Royal Sundaram',
    },
    fitness: {
      valid: true,
      expiryDate: '2026-05-30',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-03-20',
    },
    permit: {
      valid: true,
      expiryDate: '2026-06-10',
      permitType: 'Goods Carrier',
    },
  },

  // Pending Approval Vehicles
  {
    title: 'Eicher Starline School Bus - 45 Seater',
    manufacturer: 'Eicher Motors',
    vehicleModel: 'Starline',
    year: 2020,
    type: 'school-bus',
    price: 1350000,
    registrationNumber: 'PB-11K-1111',
    mileage: 52000,
    condition: 'good',
    features: ['GPS Tracking', 'CCTV Cameras', 'Fire Safety Equipment', 'Emergency Exit', 'Speed Governor'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    description: 'Reliable school bus with good service history. All safety certificates up to date.',
    isPriority: false,
    status: 'pending',
    insurance: {
      valid: true,
      expiryDate: '2026-08-15',
      provider: 'New India Assurance',
    },
    fitness: {
      valid: true,
      expiryDate: '2026-07-20',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-06-30',
    },
    permit: {
      valid: true,
      expiryDate: '2026-09-01',
      permitType: 'State Permit',
    },
  },
  {
    title: 'Force Urbania 13 Seater Luxury Van',
    manufacturer: 'Force Motors',
    vehicleModel: 'Urbania',
    year: 2022,
    type: 'minibus',
    price: 1250000,
    registrationNumber: 'WB-12L-2222',
    mileage: 18000,
    condition: 'excellent',
    features: ['Premium AC', 'Captain Seats', 'Entertainment System', 'Ambient Lighting', 'Refrigerator', 'Premium Audio'],
    images: [
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800',
    ],
    description: 'Ultra-luxury van with premium features. Perfect for VIP guest transportation and executive travel.',
    isPriority: false,
    status: 'pending',
    insurance: {
      valid: true,
      expiryDate: '2027-01-30',
      provider: 'HDFC Ergo',
    },
    fitness: {
      valid: true,
      expiryDate: '2027-02-15',
    },
    roadTax: {
      valid: true,
      expiryDate: '2027-01-10',
    },
    permit: {
      valid: true,
      expiryDate: '2027-03-01',
      permitType: 'All India Permit',
    },
  },
  {
    title: 'Ashok Leyland Dost Pickup - 1 Ton',
    manufacturer: 'Ashok Leyland',
    vehicleModel: 'Dost',
    year: 2021,
    type: 'truck',
    price: 420000,
    registrationNumber: 'OD-13M-3333',
    mileage: 24000,
    condition: 'excellent',
    features: ['Fuel Efficient', 'Easy Maneuverability', 'Strong Build', 'Service Records Available'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    description: 'Compact yet powerful pickup truck. Ideal for daily utility needs and light cargo transportation.',
    isPriority: false,
    status: 'pending',
    insurance: {
      valid: true,
      expiryDate: '2026-10-20',
      provider: 'Cholamandalam MS',
    },
    fitness: {
      valid: true,
      expiryDate: '2026-11-15',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-09-30',
    },
    permit: {
      valid: true,
      expiryDate: '2026-12-10',
      permitType: 'Goods Carrier',
    },
  },

  // More diverse options
  {
    title: 'SML ISUZU School Bus - 38 Seater',
    manufacturer: 'SML ISUZU',
    vehicleModel: 'S7',
    year: 2019,
    type: 'school-bus',
    price: 1150000,
    registrationNumber: 'AP-14N-4444',
    mileage: 68000,
    condition: 'good',
    features: ['GPS', 'CCTV', 'First Aid', 'Fire Extinguisher', 'Speed Governor', 'Emergency Door'],
    images: [
      'https://images.unsplash.com/photo-1570125909517-53cb21c89ff2?w=800',
    ],
    description: 'Japanese technology school bus with excellent fuel efficiency. Well-maintained with complete service history.',
    isPriority: false,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2025-09-30',
      provider: 'Future Generali',
    },
    fitness: {
      valid: true,
      expiryDate: '2025-11-15',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-02-01',
    },
    permit: {
      valid: true,
      expiryDate: '2025-10-20',
      permitType: 'State Permit',
    },
  },
  {
    title: 'Bharat Benz School Bus - 50 Seater',
    manufacturer: 'Bharat Benz',
    vehicleModel: '914R',
    year: 2021,
    type: 'school-bus',
    price: 1650000,
    registrationNumber: 'TS-15O-5555',
    mileage: 35000,
    condition: 'excellent',
    features: ['Premium Safety Features', 'GPS', '8 CCTV Cameras', 'Climate Control', 'Comfortable Seats', 'Anti-Lock Braking'],
    images: [
      'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',
    ],
    description: 'Premium German engineering school bus with top-tier safety features. Almost new condition.',
    isPriority: true,
    status: 'approved',
    insurance: {
      valid: true,
      expiryDate: '2026-12-31',
      provider: 'IFFCO Tokio',
    },
    fitness: {
      valid: true,
      expiryDate: '2027-01-15',
    },
    roadTax: {
      valid: true,
      expiryDate: '2026-11-30',
    },
    permit: {
      valid: true,
      expiryDate: '2027-02-28',
      permitType: 'All India Permit',
    },
  },
];
